services:
  nest:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - NODE_ENV=development
    volumes:
      - ./src:/usr/apps/src
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=task1
      - MYSQL_USER=ROOT
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'
